/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application

    kotlin("plugin.serialization") version "2.2.20"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testImplementation("io.mockk:mockk-jvm:1.14.7")
    testImplementation("io.ktor:ktor-server-test-host-jvm:3.3.3")
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test-jvm:1.10.2")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation("org.testcontainers:testcontainers:2.0.2")
    testImplementation("org.testcontainers:postgresql:1.21.3")
    testImplementation(kotlin("test"))

    // This dependency is used by the application.
    implementation(libs.guava)

    implementation("io.ktor:ktor-server-core-jvm:3.3.3")
    implementation("io.ktor:ktor-server-netty-jvm:3.3.3")
    implementation("io.ktor:ktor-server-request-validation-jvm:3.3.3")
    implementation("io.ktor:ktor-server-status-pages-jvm:3.3.3")
    implementation("io.ktor:ktor-server-content-negotiation-jvm:3.3.3")
    implementation("io.ktor:ktor-server-status-pages-jvm:3.3.3")
    implementation("io.ktor:ktor-server-call-logging:3.3.3")
    implementation("io.ktor:ktor-serialization-kotlinx-json:3.3.3")
    implementation("io.ktor:ktor-server-config-yaml-jvm:3.3.3")

    implementation("ch.qos.logback:logback-classic:1.5.22")

    implementation("io.ktor:ktor-client-content-negotiation-jvm:3.3.3")

    implementation("org.valiktor:valiktor-core:0.12.0")

    implementation("org.jetbrains.exposed:exposed-core:1.0.0-beta-1")
    implementation("org.jetbrains.exposed:exposed-jdbc:1.0.0-beta-1")
    implementation("org.jetbrains.exposed:exposed-java-time:1.0.0-beta-1")
    implementation("org.jetbrains.exposed:exposed-money:1.0.0-beta-1")
    implementation("org.postgresql:postgresql:42.7.8")
    implementation("org.xerial:sqlite-jdbc:3.51.1.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "io.ktor.server.netty.EngineMain"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
